apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginxdefargons
  namespace: dsm-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: kappa
  source:
    path: argo-temp
    repoURL: https://github.com/velann21/argo-cd.git