apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginxdef
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: argo-temp
    repoURL: https://github.com/velann21/argo-temp
    targetRevision: HEAD