apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginxdefargons
  namespace: dsm-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: kappa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: argo-temp
    repoURL: https://github.com/velann21/argo-cd.git
    helm:
      parameters:
      - name: imageTag
        value: nginx:1.14.2
      - name: replica
        value: "3"