apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginxdefault
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: argo-temp
    repoURL: https://github.com/velann21/argo-temp
    targetRevision: HEAD